### ISSUE TITLE
Queue node does not push data while connected

### ISSUE THREAD

**Issue by Pylot-KZN** [damoclark/node-red-contrib-msg-queue#12]
I am using the Queue node to persist SQL queries if there is not active connection to the database. The issue is, the Queue node seems to be just queueing the queries and storing them to the sqlite file even though the SQL node has a connected status. I have tried using the Status node to trigger the Queue node but nothing has worked.

I am using:
Raspberry Pi 4
Node JS v10.21.0
NPM v5.8.0
![Screenshot from 2020-11-20 00-07-37](https://user-images.githubusercontent.com/49070545/99730119-982d6300-2ac4-11eb-8ad1-f1c485f08990.png)

**Comment by damoclark** [comment]
You are missing a status node to provide input to the queue node on the status of your Output Coils.  Take a look at the screenshot in the [overview](https://github.com/damoclark/node-red-contrib-msg-queue#overview) section.

**Comment by Pylot-KZN** [comment]
I had initially tried using the status node, it did not seem to work. Or so I thought. The SQL node will have different status texts for when connected and disconnected. This was my issue, fixed it by wiring in a function node fed from the status node, and I use that to trigger the queue. Thanks for your insight @damoclark
