### ISSUE TITLE
Queue node storing messages indefinitely

### ISSUE THREAD

**Issue by naveen26246** [damoclark/node-red-contrib-msg-queue#2]
I am trying to add the queue node prior to Azure IOT hub node. I notice that the queue keeps storing messages without forwarding. However if I send any input to the azure iot hub node, the queue forwards the data stored so far. Am I missing out on something? Please let me know.

**Comment by damoclark** [comment]
Hi Naveen,

I'm not familar with the Azure IOT hub node.  Without further details of what you are trying to do and how your flow is set up, it is difficult to help.  But you will need to check the status output generated by the Azure node and make sure that the match you have specified for queue is correct.

Essentially, the queue node is told whether to store, or forward based on the 'status' messages that are also sent to its input.  Have you put a debug node on the status node from Azure to see what it is generating?

Damo.
